from PatternCount import PatternCount

def FrequentWords(Text, k):
    FrequentPatterns = []
    Count = [None] * (len(Text) - k + 1)
    for i in range(len(Text) - k + 1):
        Pattern = Text[i:i+k]
        Count[i] = PatternCount(Text, Pattern)
    maxCount = max(Count)
    for i in range(len(Text) - k + 1):
        if Count[i] == maxCount:
            FrequentPatterns.append(Text[i:i+k])
    return sorted(list(set(FrequentPatterns)))

Text = 'ACCCGTCGGTTAAAACCCTGTCCCTCACGAATCACGAATGGTTAAAACCACGAATACCCGTCCACGAATGGTTAAAACACCCGTCTCGCGGTTTACCCGTCGGTTAAAACGGTTAAAACTCGCGGTTTCCTGTCCCTTCGCGGTTTTCGCGGTTTTCGCGGTTTCCTGTCCCTCCTGTCCCTACCCGTCCACGAATACCCGTCGGTTAAAACCACGAATTCGCGGTTTTCGCGGTTTCACGAATCCTGTCCCTCCTGTCCCTTCGCGGTTTGGTTAAAACTCGCGGTTTACCCGTCGGTTAAAACTCGCGGTTTGGTTAAAACACCCGTCCACGAATACCCGTCACCCGTCCACGAATCACGAATCCTGTCCCTGGTTAAAACCCTGTCCCTCACGAATTCGCGGTTTGGTTAAAACCACGAATTCGCGGTTTACCCGTCGGTTAAAACACCCGTCGGTTAAAACCCTGTCCCTACCCGTCTCGCGGTTTTCGCGGTTTCACGAATCACGAATCCTGTCCCTTCGCGGTTTTCGCGGTTTGGTTAAAACCACGAATCCTGTCCCTTCGCGGTTTGGTTAAAACCACGAATCACGAATGGTTAAAACCCTGTCCCTACCCGTCCCTGTCCCTCACGAATCCTGTCCCTACCCGTCCCTGTCCCTTCGCGGTTTGGTTAAAACGGTTAAAACCCTGTCCCTCCTGTCCCTCCTGTCCCTTCGCGGTTTTCGCGGTTTCCTGTCCCTACCCGTCCCTGTCCCTCCTGTCCCTACCCGTCTCGCGGTTTGGTTAAAACGGTTAAAACACCCGTCGGTTAAAACGGTTAAAACCACGAATCCTGTCCCT'
k = 14
print(FrequentWords(Text, k))